# netlify.toml
[build]
  publish = "dist"
  command = "npm run build"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[headers]]
  for = "/static/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.css"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/*.js"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

[[headers]]
  for = "/index.html"
  [headers.values]
    Cache-Control = "no-cache"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    Referrer-Policy = "strict-origin-when-cross-origin"

[context.production.environment]
  VITE_API_URL = "https://your-render-backend.onrender.com/api"
  VITE_APP_VERSION = "1.0.0"
  VITE_ENVIRONMENT = "production"

[context.deploy-preview.environment]
  VITE_API_URL = "https://your-render-backend.onrender.com/api"
  VITE_APP_VERSION = "1.0.0"
  VITE_ENVIRONMENT = "preview"