name: Sync Excel Files from OneDrive

on:
  schedule:
    - cron: '30 9,10,12,14,16 * * 1-5'
  workflow_dispatch:

jobs:
  sync-excel-files:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests pandas openpyxl
          
      - name: Debug environment
        run: |
          echo "GitHub workspace: $GITHUB_WORKSPACE"
          ls -la
          mkdir -p data
          
      - name: Fetch Excel files from OneDrive
        run: python .github/scripts/download_onedrive_files.py
        env:
          SPARE_PARTS_INVENTORY_URL: ${{ secrets.SPARE_PARTS_INVENTORY_URL }}
          
      - name: Check downloaded files
        run: |
          ls -la data/
          echo "File sizes:"
          for file in data/*.xlsx; do
            if [ -f "$file" ]; then
              echo "  $(basename "$file"): $(stat -c%s "$file") bytes"
            fi
          done
          
      - name: Upload Excel file to backend via API
        if: hashFiles('data/Spare_Parts_Inventory.xlsx') != ''
        run: |
          echo "Uploading Excel file to backend..."
          if [ -f "data/Spare_Parts_Inventory.xlsx" ]; then
            curl -X POST \
              -F "excel=@data/Spare_Parts_Inventory.xlsx" \
              "https://vikram-spare-parts-management.onrender.com/api/sync-excel" \
              --max-time 60 \
              --retry 3 \
              -v
          else
            echo "Excel file not found for upload"
          fi
          
      - name: Force file differences check
        id: git-check
        run: |
          touch data/.files_changed_$(date +%s)
          echo "changes=true" >> $GITHUB_OUTPUT
          echo "Files have been updated - forcing commit at $(date)"
          
      - name: Commit and push if there are changes
        if: steps.git-check.outputs.changes == 'true'
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          git add data/
          git commit -m "📊 Update Excel files from OneDrive - $(date '+%Y-%m-%d %H:%M:%S')"
          git push
          
      - name: Summary
        run: |
          echo "📊 Sync Summary:"
          echo "==============="
          echo "Timestamp: $(date)"
          echo "Files processed:"
          for file in data/*.xlsx; do
            if [ -f "$file" ]; then
              echo "  ✅ $(basename "$file")"
            fi
          done
          echo ""
          echo "🔄 Next sync scheduled for every 2 hours during weekdays (9AM-5PM)"
          echo "🚀 Dashboard will auto-refresh with latest data"
